### ISSUE TITLE
Build Front-End Web Applications from Scratch Course to be Completed

### ISSUE THREAD

**Issue by r00bal** [r00bal/The-minesweeper-JS#2]
## TODO

*Steps left to complete the Minesweeper Project*

- [x] - Dynamically Generate Game Board
- [x] - Player Interactivity
- [x] - Add Class Structure
- [x] - In the Terminal - finishing touches

Action ! :clapper:
